In [3]:
import numpy as np
import pandas as pd

## 1. variables

In [4]:
x=5
x

5

In [5]:
x*2
x**2
x/float(2)

2.5

## 2. list

### 2.1 一维

In [6]:
a='is'
b=2
list_1 = ['my','list',a,b]
list_1

['my', 'list', 'is', 2]

In [7]:
list_1[0]

'my'

In [8]:
list_1[1:2]

['list']

In [9]:
list_1 + list_1

['my', 'list', 'is', 2, 'my', 'list', 'is', 2]

In [10]:
list_1 * 2

['my', 'list', 'is', 2, 'my', 'list', 'is', 2]

In [11]:
list_1.index('my')

0

In [12]:
list_1.count('is') #计数

1

In [13]:
list_1.append("!!")
list_1

['my', 'list', 'is', 2, '!!']

In [14]:
list_1.pop() # 取，但不会删除

'!!'

In [15]:
len(list_1) #长度

4

### 2.2 二维

In [16]:
lists = [[] for i in range(3)]
lists

[[], [], []]

In [17]:
# 重新初始化之后再运行
for i in range(2):
    lists[0].append(i)
for j in range(3):
    lists[1].append(j)
for k in range(4):
    lists[2].append(k)

lists

[[0, 1], [0, 1, 2], [0, 1, 2, 3]]

In [18]:
for row in range(len(lists)):
    for column in range(len(lists[row])):
        print(lists[row][column])

0
1
0
1
2
0
1
2
3


## 3. numpy array

In [19]:
list_2 = [1,2,3,4]
list_2

[1, 2, 3, 4]

In [20]:
array_1 = np.array(list_2)
array_1

array([1, 2, 3, 4])

In [21]:
array_2 = np.array([[1,2,3],[4,5,6]]) #两层中括号
array_2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
array_2[:,0]

array([1, 4])

### 3.1 运算

In [23]:
array_2 > 2

array([[False, False,  True],
       [ True,  True,  True]])

In [24]:
array_2 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
array_2 + np.array([7,8,9])

array([[ 8, 10, 12],
       [11, 13, 15]])

### 3.2 函数（方法）

In [26]:
array_2.shape

(2, 3)

In [27]:
#axis=0加入一行
np.append(array_2, np.array([[7,8,9]]),axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3.3 统计

In [28]:
array_1 = np.array([1,2,3,4,5])

In [29]:
np.mean(array_1)

3.0

In [30]:
np.median(array_1)

3.0

In [31]:
#numpy按照总体来计算，除以的是N
np.var(array_1)

2.0

In [32]:
np.std(array_1)

1.4142135623730951

## 4. NumPy

### 4.1 创建numpy array

In [33]:
# 1-dimension (可以看作2维的特殊情况？)
a = np.array([1,2,3])
a

array([1, 2, 3])

In [34]:
# 2-dimension
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [35]:
# 3-dimension
c = np.array([[(1.5,2,3),(4,5,6)], [(3,2,1),(4,5,6)]], 
             dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### 4.2 初始化array（供后续使用）

In [36]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [38]:
# 指定间距
np.arange(1,10,3)

array([1, 4, 7])

In [39]:
# 指定个数
np.linspace(1,2,8)

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        ])

In [40]:
# 对角1 (identity matrix)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.random.random((2,0))

array([], shape=(2, 0), dtype=float64)

### 4.3 检查array

In [42]:
c.shape

(2, 2, 3)

In [43]:
# 这个有意思
len(c)

2

In [44]:
c.ndim

3

In [45]:
c.size

12

In [46]:
c.dtype

dtype('float64')

### 4.4 数学计算

In [47]:
a-b

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [48]:
a*b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [49]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [50]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 4.5 比较

In [51]:
# 注意返回的结果
a == b

array([[False,  True,  True],
       [False, False, False]])

### 4.6 总体情况

In [52]:
b.sum()

21.5

In [53]:
b.min()

1.5

In [54]:
# 所以两种写法都可以
b.mean()

3.5833333333333335

In [55]:
b.std()

1.5920810978785667

### 4.7 切片

In [56]:
b[0:2,1]

array([2., 5.])

### 4.8 变形

In [57]:
b.reshape(3,2) # 不改变原值

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [58]:
np.concatenate(([a],b),axis=0)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## 5. Pandas

### 5.1 数据结构

In [59]:
# Series
s = pd.Series([3, -5, 7, 4], index=['a','b','c','d'])
s

a    3
b   -5
c    7
d    4
dtype: int64

In [60]:
# DataFrame
df = pd.DataFrame(
{
    'Country':['Belgium','India','Brazil'],
    'Capital':['Brussels','New Delhi','Brasilia'],
    'Population':[11190846,1303171035,207847528]
},
columns=['Country','Capital','Population'])
df

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

### 5.2 取数

In [61]:
s['b']

-5

In [62]:
df[1:2]

Country    Capital  Population
1   India  New Delhi  1303171035

In [63]:
# 用行列号取
df.iloc[:,[0,2]]

Country  Population
0  Belgium    11190846
1    India  1303171035
2   Brazil   207847528

In [64]:
# 用列名取
df.loc[:,['Country','Population']]

Country  Population
0  Belgium    11190846
1    India  1303171035
2   Brazil   207847528

In [65]:
df.drop('Capital',axis=1) # 必须指明是列名，不会改变原数据

Country  Population
0  Belgium    11190846
1    India  1303171035
2   Brazil   207847528

### 5.3 总体情况

In [66]:
df.shape # 查看对象的一个‘属性’，所以不用括号

(3, 3)

In [67]:
df.columns

Index(['Country', 'Capital', 'Population'], dtype='object')

In [68]:
df.count(axis=1) # 对对象进行了操作，所以有括号

0    3
1    3
2    3
dtype: int64

In [69]:
df.describe()

Population
count  3.000000e+00
mean   5.074031e+08
std    6.961346e+08
min    1.119085e+07
25%    1.095192e+08
50%    2.078475e+08
75%    7.555093e+08
max    1.303171e+09

### 5.4 匿名函数

In [70]:
f_lambda = lambda x: x*2

In [71]:
df.apply(f_lambda) # 不改变原数据

Country             Capital  Population
0  BelgiumBelgium    BrusselsBrussels    22381692
1      IndiaIndia  New DelhiNew Delhi  2606342070
2    BrazilBrazil    BrasiliaBrasilia   415695056

In [72]:
df

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528

## 6. 数据读取

### 6.1 stata数据

In [74]:
heights = pd.read_stata(
    "/Users/riliu/Documents/Programming/JupyterProjects/data/heights.dta")

In [75]:
heights

sex    age  height  weight  spouses_height
0     MALE   11.0   164.8    75.0          164.00
1   FEMALE   17.0   164.0    56.0          164.00
2   FEMALE   25.0   163.0    54.5           -2.00
3     MALE   30.0   169.5    69.0           -2.00
4     MALE   35.0   171.5    69.0          159.00
5   FEMALE   44.0   159.4    57.0          171.00
6     MALE   65.0   178.9    93.5          149.00
7   FEMALE   79.0   149.9    51.0          178.00
8     MALE   20.0   174.6    70.5          165.50
9   FEMALE   35.0   165.5    43.5           -2.00
10  FEMALE   15.0   162.4    55.0           -2.00
11    MALE  999.0   180.9    80.5          159.00
12  FEMALE   75.0   159.0    70.0          180.00
13    MALE   34.0   182.8    78.5           -2.00
14    MALE   56.0   196.9   117.0           -2.00
15    MALE   76.0   186.5    67.5           -2.00
16    MALE   32.0   163.0    58.5           -2.00
17    MALE   11.0   177.5    81.0          156.00
18  FEMALE   22.0   156.4    57.0          177.00
19    MALE   33.0   166.9    69.0          149.00
20  FEMALE   44.0   149.9    58.5          166.00
21    MALE   55.0   172.5    90.5          163.00
22  FEMALE  999.0   163.9    60.5          172.00
23    MALE   53.0   178.0    81.0           -2.00
24  FEMALE   63.0   163.1    58.0           -2.00
25    MALE   73.0   176.6    84.5          156.69
26  FEMALE   74.0   156.6    70.0           -2.00
27  FEMALE   88.0   162.9    52.0           -2.00
28    MALE   13.0   171.9    77.0          160.19
29  FEMALE   46.0   160.1    49.5           -2.00
30    MALE   40.0   171.6    70.0          164.50
31  FEMALE  999.0   164.5    76.5           -2.00
32  FEMALE   47.0   162.1    52.0           -2.00
33  FEMALE   22.0   149.0    71.5           -2.00
34  FEMALE   25.0   147.6    50.0           -2.00
35    MALE   28.0   176.5    60.0           -2.00
36    MALE   32.0   171.1    73.5          169.20
37  FEMALE   58.0   169.1    63.5           -2.00
38    -2.0  999.0    -1.0     0.0           -2.00
39    MALE   32.0   176.5    83.0           -2.00
40    MALE   32.0   163.4    65.5          155.00
41  FEMALE   53.0   155.0    43.0          163.00
42    MALE   68.0   184.1    80.5          156.00
43  FEMALE   34.0   156.6    56.5          184.00
44    MALE   11.0   171.5    57.0          149.00
45  FEMALE   32.0   149.8    50.0          171.00
46    MALE   18.0   179.3    73.0           -2.00
47    -2.0   38.0   170.0     0.0          162.00
48  FEMALE   42.0   162.0    83.5          170.00
49    MALE   88.0   175.5    80.0          168.00

### 6.2 csv数据

In [77]:
heights_valid = pd.read_csv(
    "/Users/riliu/Documents/Programming/JupyterProjects/data/heights_valid.csv")

In [ ]:
heights_valid